### ISSUE TITLE
Update meta information

### ISSUE THREAD

**Issue by NickSettler** [House-Manager-CZ/house_frontend#16]
## Meta information update

- [ ] Update app icons
- [ ] Update app title
- [ ] Update app description
